### ISSUE TITLE
보고서 생성 완료 토픽의 record 타입 결정

### ISSUE THREAD

**Issue by suna-ji** [DevPalsBoot/event-driven-kafka#7]
### 📝 **보고서 생성 완료 토픽 Record 타입 결정**

---

#### 🗂 **배경**
보고서 생성 완료 후 보고서 서버가 발행하는 "REPORT_COMPLETION" 토픽의 record 타입을 결정해야 합니다.

#### 💡 **의사결정 항목**
1. record에 생성 완료된 보고서의 byteArray를 넣어서 보낸다.
3. record에는 간단한 정보만 넣고 생성 완료된 보고서는 s3에 올리고 백엔드가 s3에 접근한다,

#### 🔍 **검토할 사항**
[카프카 message limit 공식 문서 링크](https://kafka.apache.org/documentation/#brokerconfigs_message.max.bytes)
다운로드 센터 UI/UX 고려해야함
- 파일 생성 후 다운로드 계속 가능하게 할건지 -> 그렇다면 S3에 파일 올려야 함
- 보고서 파일 크기 -> 제한이 없음 계속 늘어날 수 있음

#### 📌 **추가 코멘트**
- 기타 필요한 사항이나 의견을 남겨주세요.

---

**Comment by since1909** [comment]
의사결정 항목 1번
파일 사이즈 제한이 없는 상황이므로 바이트 배열 전체를 레코드에 넣지 않는게 좋을 것 같습니다.
생성된 보고서 파일 재다운로드가 가능하도록 구현하려면 **2번 선택지가 좀 더 합리적** 으로 보입니다.

**Comment by suna-ji** [comment]
2번 선택지로 진행합니다.
