### ISSUE TITLE
보고서 생성 완료 이벤트 record value 정의

### ISSUE THREAD

**Issue by suna-ji** [DevPalsBoot/event-driven-kafka#9]
### 📝 **보고서 생성 완료 이벤트 record value 정의**

---

#### 🗂 **배경**
현재는 String 타입의 메시지만 생성 완료 이벤트의 record value값으로 넣고 있음
어떤 정보를 value값에 넣어야 백엔드가 보고서 다운로드를 할 수 있을지 찾아보고 정해야한다.

#### 💡 **의사결정 항목**
- s3 object path
- 상태 값 (성공, 실패)

#### 📌 **추가 코멘트**

---

**Comment by since1909** [comment]
보고서 생성 완료 메시지 타입 정의됨에 따라 백엔드 consume 메소드 타입 string -> object 로 변경
